### PR TITLE
Add support for KernelCapabilities

### PR DESCRIPTION
**Pull request by vladaurosh**
This commit adds option to add kernel capabilities for ECS task definition.  Relevant GutHub issue is [#241](https://github.com/jenkinsci/amazon-ecs-plugin/issues/241).

It's described [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_linuxparameters).

Currently, Fargate supports just SYS_PTRACE kernel capability, EC2 ECS supports everything on the link above.

I have tested this with Fargate, and it works fine, haven't tested with EC2 ECS.

NOTE: This adds option to add kernel capabilities, I haven't implemented option to drop capabilities, but should be easy to add, though I think it's rarely being used.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by vladaurosh** [comment]
Hello @Stericson 

I am glad to see that support for this plugin is live again. Looking forward to new version.

Any plans to include this PR? And #237 especially.

**Comment by Stericson** [comment]
Hello @vladaurosh, 

I planned to follow up on the remaining PRs after the release I plan on doing this week. 

More specifically, I'd like for those who have these PRs open to resolve the merge conflicts before approving/merging them.

If you'll resolve the merge conflicts here I'll review and work to get it into an upcoming release.

Thanks,
Stephen

**Comment by vladaurosh** [comment]
Hi @Stericson 

I've just resolved merge conflicts. 

Thanks in advance.

**Comment by Stericson** [comment]
@vladaurosh thanks! I'll get it into the next release.

**Pull request merged**
