### PR TITLE
Add support for setting ulimit configuration

### PR DESCRIPTION
**Pull request by jcragg**
I noticed that the plugin was lacking the ability to set the ulimit configuration values for ECS containers, so I've added support for this.

### CODE REVIEW

**Comment by pgarbe** [comment]
Hi @jcragg, can you please rebase your fork to solve the conflicts?

**Comment by jcragg** [comment]
Done.

**Comment by hemp** [comment]
Looks like this build might have died resolving dependencies and could be kicked off again: `Return code is: 502 , ReasonPhrase:Bad Gateway.`

**Comment by pgarbe** [comment]
I'm looking into adding support for existing task definitions (#45 or #50). That would make it easier whenever ECS adds new options, because the plugin doesn't need to be updated/adopted. 

Would that help you?

**Comment by domofactor** [comment]
@pgarbe yup, that works for me 👍

**Comment by pgarbe** [comment]
Merged #50, so ulimits (and others) can be configured directly in a task definition.

**Comment by qmcyruss** [comment]
> Merged #50, so ulimits (and others) can be configured directly in a task definition.

Can I defile ulimits in the plugins?

**Comment by qalinn** [comment]
@pgarbe  Could you give me an example how is possible to set ulimit directly in a task definition?

**Comment by pgarbe** [comment]
Sorry, I left the project almost 2 years ago. Maybe @jcragg can help you?

**Comment by qalinn** [comment]
@jcragg  Could you give me an example how is possible to set ulimit directly in a task definition?

**Pull request closed without merging**
