### PR TITLE
Add taskRoleArn configuration option

### PR DESCRIPTION
**Pull request by roehrijn**
This will add the possibility to assign an IAM role to the slave ECS task definition.
To do this I needed to update the dependency to the newer AWS SDK, because adding a task role is not supported in the old version.

### CODE REVIEW

**Comment by roehrijn** [comment]
@joh-m some thoughts about your change:

1. I would suggest to add at least a short explanation to the configuration screen what the purpose of the new taskRoleArn field is and how to use is. Hope you agree.
2. Wouldn't it be better not to call `#withTaskRoleArn(...)` ith no ARN is supplied in configuration?

**Comment by bonclay7** [comment]
Hello !
It would be really appreciated to see this feature coming in the plugin.
There are some cases where slaves nodes needs particular IAM roles that ECS container instance does not need to have. 
Today, we have to manually update the task definition to include ECS Task Role and edit the Jenkins config file to update the task revision. 

It will be really cool have this option on the Jenkins interface :)

**Comment by dipthegeezer** [comment]
@roehrijn 

Just to get some movement on this ticket, it's fine to call withTaskRoleArn(...) with a null value.

**Comment by joh-m** [comment]
would also like to see some movement here. I would add some description in a separate PR as I cannot update this anymore, but as @dipthegeezer says calling withTaskRoleArn with null should be fine

**Comment by LiamMaru** [comment]
I'm keen to see this move forward. Are there any roadblocks to this being merged?

**Pull request merged**
