### PR TITLE
Support AWS region. Setting AWS region in jenkins system setting screen.

### PR DESCRIPTION
**Pull request by azuchi**
Current Plugin use us-east-1 region only, so this pull request support other AWS region. 
Specify AWS region in Jenkins System Setting screen.

### CODE REVIEW

**Comment by ajohnstone** [comment]
Having exactly the same issue, would be great to get this merged asap :+1:

**Comment by ndeloof** [comment]
@azuchi LGTM
can you please rebase so I can merge ?

**Comment by azuchi** [comment]
Sorry, merge failure. so I create another pull request.

**Comment by ndeloof** [comment]
you can just rebase on master and push force to your PR branch to update this one

**Pull request closed without merging**
