### PR TITLE
Support Fargate EphemeralStorageSize

### PR DESCRIPTION
**Pull request by steven-aerts**
Enable EphemeralStorageSize allows you to increase the size of the root
disk up to 100GB.  Only support for Fargate 1.4.0 and above.
As this requires AWS java SDK version 2.11.1008 some extra depdencies
needed to be updated.

### CODE REVIEW

**Comment by vladaurosh** [comment]
Hello @steven-aerts 
Would you be able to resolve merge conflicts so this PR is included in next release?

**Comment by Stericson** [comment]
@steven-aerts 👋 Hello, if you'll resolve the conflicts here in your PR I'll take a look into getting it merged.

**Comment by vladaurosh** [comment]
Hey @Stericson 
Is it possible to copy changes that @steven-aerts made? I am sure he/she wouldn't mind.

**Comment by steven-aerts** [comment]
@Stericson @vladaurosh 

I rebased everything.  Hope you will enjoy this new feature as much as we do.

**Review by Stericson — APPROVED** [review]

**Comment by Stericson** [comment]
@steven-aerts Thanks! Merged the change in. I'll get it into a future release. Thanks for the contribution!

**Comment by dcacenabes** [comment]
@steven-aerts thanks a bunch for implementing this.

@Stericson is there any way we can help you trigger a release including this anytime soon? We are running out of space with the default size, and are really looking forward to be able to define larger ephemeral storage.

**Comment by Stericson** [comment]
@dcacenabes I can get a release out later this week.

**Comment by dcacenabes** [comment]
> @dcacenabes I can get a release out later this week.

Thank you so much @Stericson 🙏  Looking forward to it!

**Comment by Stericson** [comment]
@dcacenabes @steven-aerts New Release is out!

**Comment by dcacenabes** [comment]
Thank you!!!! This is great news!! Updating...

**Pull request merged**
