### PR TITLE
Dynamic tagging support

### PR DESCRIPTION
**Pull request by ugurkany**
This PR adds support for custom tagging on the task definition level. Also, you can define dynamic tags that are specific to builds.

Relevant PR:
https://github.com/jenkinsci/amazon-ecs-plugin/pull/272

The main difference with the PR above is you can define specific tags to task definitions via Jenkins GUI on this PR.

Resolves following issues:
https://github.com/jenkinsci/amazon-ecs-plugin/issues/256
https://github.com/jenkinsci/amazon-ecs-plugin/issues/261

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by Stericson** [comment]
@ugurkany Would you mind resolving the conflicts here?

**Comment by ugurkany** [comment]
@Stericson Sorry for the late response. These conflicts cause by merging the other PR. It had a few missing points like defining tags with GUI or via declarative Pipeline on the other PR. I didn't test other PR, but as far as I see on the code, it overrides the tags already defined on AWS manually. I hope that won't be an issue in some cases. And without propagation, how will AWS tasks collect tags from task definition? Users need to configure this manually after the creation of the task definition. I prefer to merge this if I were in your shoes. So solving conflicts won't be enough. I need to recode the extra things that I developed.

**Comment by Stericson** [comment]
@ugurkany I see your points. I'll take a look at this more in depth on Monday.

**Comment by Stericson** [comment]
@ugurkany Merged 👍

**Comment by charbl** [comment]
question, if I wanted the tag to contain the env var JOB_NAME (the active job) ... how would i setup the task def to contain this and pull that info when the job is run?

**Pull request merged**
