### PR TITLE
Add link to tutorial.

### PR DESCRIPTION
**Pull request by tkgregory**
Link to tutorial about running jobs on ECS slave agents. I think this would be a helpful resource for anyone wanting to get started with this plugin.

### CODE REVIEW

**Review by markyjackson-taulia — CHANGES_REQUESTED** [review]
Kindly remove the term “slave”, agent has been the terminology for some time.
Thank you.

**Comment by tkgregory** [comment]
Thanks for the suggestion @markyjackson-taulia I didn't realise. Fixed.

**Comment by markyjackson-taulia** [comment]
> Thanks for the suggestion @markyjackson-taulia I didn't realise. Fixed.

Thank you for that change. I also see on the youtube video the ref to the same word.
image

I know the video was made in 2015 but referencing that now would be incorrect. Can we not use that video?

**Comment by tkgregory** [comment]
That video link was already in the README. I just fixed the formatting.

**Comment by markyjackson-taulia** [comment]
Let's see what some of the other maintainers say. My vote is a +1 to remove this video and leave the slides.

**Pull request closed without merging**
