### PR TITLE
Add support for specifying Task Execution Role ARN

### PR DESCRIPTION
**Pull request by jcragg**
Allows for specifying the Task Execution Role which is required for a few different ECS scenarios:
  * Calls to Amazon ECR to pull the container image
  * Calls to CloudWatch to store container application logs (i.e. using the awslogs driver)

### CODE REVIEW

**Comment by pgarbe** [comment]
Merged #50, so task execution role (and others) can be configured directly in a task definition.

**Comment by chriscelebisonos** [comment]
@pgarbe I believe this is still required, as I'm not able to specify a TaskExecutionRole and do not want to use a predefined task definition.

**Comment by ccelebi** [comment]
@pgarbe I believe this is still required, as I'm not able to specify a TaskExecutionRole and do not want to use a predefined task definition.

Without this, I still hit: 
```
Unexpected` exception encountered while provisioning agent ECS Slave test-fargate
com.amazonaws.services.ecs.model.ClientException: Fargate requires task definition to have execution role ARN to support ECR images. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID:
```

**Comment by pgarbe** [comment]
I agree, that you need it, if you don't want to specify your own task definition. I'm interested why you would prefer a generated task definition from the plugin instead defining your task definition in AWS. Maybe you can elaborate a bit about your use case?

**Pull request closed without merging**
