### PR TITLE
Support for existing TaskDefinitions in AWS

### PR DESCRIPTION
**Pull request by igorvsd**
Support custom TaskDefinitions that could contain multiple docker containers (need to have jenkins-node container included).

This commit adds new type of Task : "Task Definition" to be added on settings page.

Doesn't break any existing functionality.

### CODE REVIEW

**Comment by jonsie** [comment]
This would be quite a useful feature.  What do people here think?  @igorvsd are you still wanting this to be merged?

**Comment by bbscripps** [comment]
I was actually going to look into adding functionality to allow the specification of a task role on a slave template, but this would actually solve this problem in a more long-term way for this plugin.

**Comment by dpalomin** [comment]
I would be interested in seeing this change released.

**Comment by yrsurya** [comment]
Hi,
    I tried creating my own custom plugin using your pull request but am not able to start the container can you please check the config once and let me know if I am missing anything

image

**Comment by igorvsd** [comment]
I think it's probably because you didn't specify "Task Definition Jenkins Container Name"
It should be name of the container Image in your task definition with type (ex. : jenkinsci/jnlp-slave or cloudbees/jnlp-slave-with-java-build-tools or one create by yourself of inherited from one of these 2).
Here is an example where "jenkins-node" is a sample container.
screenshot 2017-08-17 09 45 29

**Comment by yrsurya** [comment]
I guess he is the maintainer of this plugin who approves pull request 

https://stackoverflow.com/users/1728427/roehrijn?tab=profile

**Comment by rifelpet** [comment]
Given the lack of response I'm guessing that in order to get this merged and the plugin updated someone may have to [adopt](https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin) the plugin. Anyone willing to do that?

**Comment by yrsurya** [comment]
https://groups.google.com/forum/#!searchin/jenkinsci-dev/amazon-ecs%7Csort:relevance/jenkinsci-dev/lkffA4lMn2I/JO5I0h1rDgAJ

I guess these people can provide the authorization if any one interested

**Comment by pgarbe** [comment]
Many thanks for your contribution. Will close this one in favor of #50

**Pull request closed without merging**
