### PR TITLE
Add service containers

### PR DESCRIPTION
**Pull request by justinbarry**

### CODE REVIEW

**Comment by pgarbe** [comment]
@justinbarry  Can you please describe your pull requests? What's your intention? It would be also nice, if you can rebase your fork as it has some conflicts.

**Comment by CpuID** [comment]
If this is what I think it is (allowing sidecar containers to an ECS agent, within a single task definition), +100 would be extremely beneficial.

**Comment by justinbarry** [comment]
@CpuID Your suspicion is correct. I'll rebase.

**Comment by justinbarry** [comment]
@CpuID Done. Can you confirm it works? Sadly, I no longer run Jenkins and therefore have no means to test it.

**Comment by CpuID** [comment]
@justinbarry possibly, I'll see how I go during this week

**Comment by CpuID** [comment]
> @CpuID Done. Can you confirm it works? Sadly, I no longer run Jenkins and therefore have no means to test it.

Hey @justinbarry apologies haven't had a chance to test this. Our use case is relatively complexed, and we have a hand drafted task definition per template using overrides in place to fulfil our needs right now (also version controlled). I'm inclined to say we will continue down this road - especially since there is no API method to manage the list of ECS templates for this plugin.

**Comment by justinbarry** [comment]
@CpuID No problem! I think a hand rolled task def is a better way to go personally. I'll close this.

**Pull request closed without merging**
