### PR TITLE
JENKINS-33928: Communication to AWS API should support HTTP proxies

### PR DESCRIPTION
**Pull request by roehrijn**
* integrated support for using the proxy configured by
Jenkins.getInstance().proxy

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
@roehrijn that a great idea!

I think that we should honor `ProxyConfiguration.noProxyHost`. A sample to check wheither the host matches is available at: https://github.com/jenkinsci/jenkins/blob/c5759f957b8546e79d8c185ecd459a220baff857/core/src/main/java/hudson/ProxyConfiguration.java#L180

Enhancing the log message ([here](https://github.com/jenkinsci/amazon-ecs-plugin/pull/18/files#diff-6dc5ac83fb2f7e028bd535ecaaf7c0d3R210)) to indicate the proxy configuration would help troubleshooting.

**Comment by ndeloof** [comment]
LGTM as long as `ProxyConfiguration.noProxyHost` is handled

**Comment by roehrijn** [comment]
@cyrille-leclerc, sorry for that delayed answer. I moved to a new employer recently and my github account still used the old email. So no notifications about this thread reached me. 

I'm going to integrate noProxyHost handling soon and file another pull request.

**Comment by cyrille-leclerc** [comment]
Thanks @roehrijn !

**Comment by roehrijn** [comment]
@cyrille-leclerc, I spent the last view hours on finding a way how to support _noProxyHost _in combination with the aws-java-sdk. It is difficult because the SDK uses computed hostnames which depend on the service and region you choose. My first idea was to create a default AWSClient object to find out the endpoint it uses. But afaik there is no way to get this information out of _AmazonECSClient_. I can fetch the service name and use this together with the metadata delivered with the SDK (_RegionUtils_) to find out the endpoint and the hostname in consequence. But this requires the AWS SDK to be up to date. As long as as the service is not listed to be available in a region in SDK's region.xml, proxy support will fail for ECS in this region. This is the case with ECS and eu-central-1 in the latest version of the aws-java-sdk plugin of Jenkins. Latest version of the plugin is 1.10.45. The latest AWS SDK version is 1.10.69 and contains that combination.

What do you think? Is it worth these drawbacks to support _noProxyHost _feature? **I'm not sure**.

**Pull request merged**
