### PR TITLE
Add support for Tags

### PR DESCRIPTION
**Pull request by saad352**
This PR aims to add support for adding tags on AWS tasks and task definition created by plugin.

Resolves issue [**#261**](https://github.com/jenkinsci/amazon-ecs-plugin/issues/261)

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by saad352** [comment]
Hi @Stericson, Kindly have a look at this PR and review.
Thanks

**Review by Stericson — APPROVED** [review]

**Comment by saad352** [comment]
Thanks @Stericson. 
When can we expect the next release?

**Comment by Stericson** [comment]
@saad352 Yes, I'll try to get it out within the next week or two. There's one more PR open that I'd like to see merged and included so just waiting a bit on that.

**Comment by Stericson** [comment]
@saad352 Please take a look at https://github.com/jenkinsci/amazon-ecs-plugin/pull/274 

This has been merged rather than #272 because it adds support for the configuration of new tags through the Jenkins UI.

Let me know if there are any concerns and we'll get them worked out.

**Comment by saad352** [comment]
Nope @Stericson looks good. 👍

**Comment by ugurkany** [comment]
@saad352 Also, this feature will be available in the next release. (probably, we will deploy it this week.)

**Pull request merged**
