### PR TITLE
Adding Shared Memory Size options to set it within ECS

### PR DESCRIPTION
**Pull request by mboudreau**
Adding an option for `sharedMemorySize` (in MiB) which sets it for the ECS template and has been supported since March 2018.

### CODE REVIEW

**Comment by mboudreau** [comment]
Also, I noticed that the end package load `mockito-all` into the .hpi file.  Isn't mockito suppose to be in the test scope only?  Doesn't make sense to package it for release unless I'm missing something.

**Comment by mboudreau** [comment]
I've removed mockito-all from the packaging step as I'm fairly certain it's not needed.

**Comment by mboudreau** [comment]
Sorry, that's what the release packaging does automatically.  Can you tell me what's the specific version you want me to put? `1.20-SNAPSHOT`? or `-BETA`?

**Comment by webratz** [comment]
We had both in it ;) seehttps://github.com/jenkinsci/amazon-ecs-plugin/commit/8cd80d25a8b9b00cc7d6c1d606006325913898af for an example on how it looks

**Comment by mboudreau** [comment]
@webratz Changed it to 1.20-SNAPSHOT.

**Comment by webratz** [comment]
Sorry, i wasn't very clear with my earlier comment :(
Correct would be `1.21-SNAPSHOT`
After that maybe a few people can try it an we can release it a few days later

**Comment by mboudreau** [comment]
Done.

**Pull request merged**
