### PR TITLE
Add support for EFS Mount Points

### PR DESCRIPTION
**Pull request by serpentblade**
Support EFS volume mounts, including new EFS Access Point API

Added support for EFS volume mounts as part of the ECS configuration.

Resolves issue #181
This is a re-opening of #210 now that this repo has maintainers, hopefully we can get this merged this time around.

I've been using this code in production for several months without any issue, and have had others manually build and use it successfully as well (see original PR).

- [x ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x ] Ensure that the pull request title represents the desired changelog entry
- [x ] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by vladaurosh** [comment]
Hello @serpentblade 

I am using this plugin (latest version, 1.38)  and only way to mount EFS share into docker container running in Fargate is to create task definition with Volumes and Mount Points and use "Task Definition Override" in Cloud Configuration for that template.



Will this change add option to do this in "ECS Agent template"? Currently there is "Container Mount Points" section in "ECS Agent template" (screenshot below) but it throws error that this is not supported with Fargate and Volumes config is missing.

efs


Thanks

**Comment by serpentblade** [comment]
Hi @vladaurosh,

Here's a screenshot of what this PR adds to the ECS cloud configuration:
Screen Shot 2021-08-31 at 10 00 49 AM

It uses the AWS api to automatically populate a dropdown of available File System ID and Access Point ID for you to choose from and adds the appropriate configuration to the task definition.

I believe this is what you are looking for to use with Fargate.  I do not use Fargate  so can't provide you much more information, but I had a previous PR (#210) with some comments from other people that found success using it for Fargate which may provide you more assistance.  Also in that previous PR comments is steps in compiling this branch and manually uploading the plugin to your Jenkins instance if you want to try it out while I wait with hope that it can be merged.

**Comment by vladaurosh** [comment]
Hello @serpentblade 

This is awesome! Is it possible to override these settings in pipeline type of job?
For example:
 agent {
            ecs {
                inheritFrom 'label-of-my-preconfigured-template'
                cpu 2048
                memory 4096
                logDriver 'fluentd'
                logDriverOptions([[name: 'foo', value:'bar'], [name: 'bar', value: 'foo']])
                portMappings([[containerPort: 22, hostPort: 22, protocol: 'tcp'], [containerPort: 443, hostPort: 443, protocol: 'tcp']])
            }
        }

**Comment by serpentblade** [comment]
@vladaurosh, yes I believe it should also be possible to override in the ECS Agent.  I don't do it specifically, but the code is there to support so.

The pipeline configuration directive below should be the same as the example I provided in my screenshot.
```
agent {
   ecs {
      ...
      ecsMountPoints([ [ name: 'webpack-cache', containerPath: '/root/webpack-cache', readOnly: false, fileSystemId: 'fs-abcdefg', accessPointId: 'fsap-abcdefg0123456', rootDirectory: '/', transitEncryption: true, iam: false ] ])
   }
}
```

If that doesn't work, let me know and I can see about testing it in one of my pipelines to see if there's something I missed.

**Comment by vladaurosh** [comment]
Hi @serpentblade .

Thanks again. I am off in next 10 days, but I'll try it asap.

And one more question. Is it possible to override settings for freestyle type of job? Currently, you can put just label, but no further changes are possible.

**Comment by vladaurosh** [comment]
Hi @serpentblade 
I've built this plugin using your code changes, works great with Fargate.
Pipeline configuration directive works fine as well.
Only thing that perhaps could be changed is that 'Root directory' should be greyed out when Fargate is chosen. That parameter can't be changed and defaults to / when Fargate is used.

**Comment by serpentblade** [comment]
Thanks for the feedback! I'm glad to hear it is working for you.  I'll look into disabling the root directory field when using Fargate.  I believe root directory defaults to / when using a Filesystem Access Point as well, so there's another situation to make sure it is not changed for a configuration.

**Comment by vladaurosh** [comment]
Hello @serpentblade 

Would you be able to resolve merge conflicts so this PR can be merged?

Thanks in advance.

**Comment by Stericson** [comment]
Hi @serpentblade, sorry to ask this again, but would you mind resolving the new conflicts? I believe they arose from @vladaurosh's PR which was recently merged in.

**Comment by kbratanis** [comment]
Hi everyone, is this going to be included in the next release? I don't see it in 1.39.  Many thanks for the great work!

**Comment by kbratanis** [comment]
Thanks for releasing 1.40 with this feature. Really appreciated.  Some feedback: On the ECS Template UI there are dropdown controls to select the EFS FS ID and Access Point ID. Those fields are not populated if you do not have Amazon ECS Credentials for AWS configured on the same screen. This is the case when you use native IAM authentication between the Jenkins Controller and ECS, instead of access keys on the Controller.

Screenshot 2022-02-11 at 3 49 09 PM
Screenshot 2022-02-11 at 3 48 43 PM

I understand the convenience of the list, but it would be better to have a textfield instead. UX wise anyone who is configuring this plug-in will have the EFS and AP IDs in their clipboard ready to be pasted. :)  Or even better would use JCaaS.

For now the work around is to configure the EFS volume mounting through JCaaS.

Many thanks for your efforts.

**Comment by serpentblade** [comment]
@kbratanis The ECS Credentials are required in that UI to select the ECS cluster.  Would you advocate for that dropdown to be changed to a text field too?  The whole point of the UI is the convenience of being able to easily configure the ECS cloud, and the inclusion of auto-filling EFS IDs and associated file system IDs via dropdown is part of that experience.  The update to the README includes the new permissions required for this plugin, which will allow those drop downs to work.  I'd recommend updating the permissions on your managing credentials if you'd like to have access to these new features.

However it sounds like you're already an advocate for JCaaS, so the UI should have no meaning to you anyway?

**Comment by kbratanis** [comment]
@serpentblade  Hi Dan, point taken and agreed. I use the UI to test changes in the configuration and then I am persisting them in JCaaS. This flow made me stumble upon what I described earlier. But as you said, at the end of the day the UI is not a blocker for me. So yes, let's not change every dropdown! :) 

Cheers.

**Comment by TreeKat71** [comment]
Hi @serpentblade,
Thanks for your great work. I have a question, currently my Jenkins is running on EC2 and I am able to list informations with IAM role (without credential). So is there a way to use this feature without credential? 
Right now, the dropdown list is empty because I left credential blank. 
If any step I missing, please tell me and give me some advices, thanks !

**Pull request merged**
