### PR TITLE
Changes to enable ECSCloud overrides

### PR DESCRIPTION
**Pull request by pgmillon**
Hi,
I'm building a custom ECSCloud out of this plugin for some very specific needs.
To avoid duplicating everything, I just split the content of ECSLauncher.launch so I can capture the Task at some point.
I also made ECSService class public.

### CODE REVIEW

**Comment by webratz** [comment]
due to other PRs merged, this needs a rebase

**Comment by pgmillon** [comment]
Rebased onto master

**Comment by webratz** [comment]
it shows some errors during the build, could you please check https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Famazon-ecs-plugin/detail/PR-192/6/pipeline

**Comment by pgmillon** [comment]
Fixed, sorry I didn't check spotbugs locally.

**Pull request merged**
