### PR TITLE
Fix do not remove custom task.

### PR DESCRIPTION
**Pull request by connal-m**
https://github.com/jenkinsci/amazon-ecs-plugin/issues/131 Fix issue mentioned here

### CODE REVIEW

**Comment by poflynn** [comment]
When squashing this pay attention to the commit msg and ensure it has a JIra in it

**Comment by webratz** [comment]
i' m traveling the whole week, i'll try to have a look beginning of next week. maybe also @markyjackson-taulia can have alook

**Comment by conorjduggan** [comment]
@webratz @markyjackson-taulia any chance you could take a quick look please? 😄

**Comment by conorjduggan** [comment]
@webratz @markyjackson-taulia any idea when the next release might be please?

**Comment by webratz** [comment]
i'm currently traveling and will be back in around 2 weeks, will try to create a new release then

**Comment by connal-m** [comment]
@webratz Can we get a release for this please 🙏

**Comment by webratz** [comment]
just created the release, might take a few hours until its available everywhere

**Comment by webratz** [comment]
available for testing at https://repo.jenkins-ci.org/releases/com/cloudbees/jenkins/plugins/amazon-ecs/1.24/amazon-ecs-1.24.hpi

**Comment by connal-m** [comment]
Awesome thanks a million!

**Pull request merged**
