### PR TITLE
Task definition name based on cloud and Template name

### PR DESCRIPTION
**Pull request by dipthegeezer**
Hi @roehrijn 

This fix comes out from the discussion that was held in #27 about having a more flexible task definition name. I've made the changes as requested summarised as below:

- Add a new 'Template Name' configuration that has to be defined.
- Add checking to make sure Cloud and Template Name are in the right format
- Use the combination of template name and cloud name when defining a task definition.

Thanks

### CODE REVIEW

**Comment by roehrijn** [comment]
@dipthegeezer, thanks for the work. I looked over the code and it looks good so far. Hopefully I'll find the time to test it in my system on Thursday or Friday this week. 
Just two additional minor thoughts:

- what about the existing cloud definitions which contained spaces before the plugin update to the new version?
- same with template name. Additionally shouldn't we provide an option to automatically fill the template name if not supplied?

**Comment by dipthegeezer** [comment]
hi @roehrijn 

-  I'm open on solutions to how to fix this. This maybe a problem.
-  The template name is a new field so, it should not have an effect on existing cloud definitions. However I think you are right and we should define a default. I will make this change.

**Comment by roehrijn** [comment]
Hi @dipthegeezer,

what about removing spaces from cloud name before using it in the AWS API? This would make it work even with spaces. Later, when users change something in the cloud definition the validation makes sure spaces to be eliminated.

**Comment by dipthegeezer** [comment]
@roehrijn

That sounds like a plan. I can make those changes when I get a spare moment.

**Comment by dipthegeezer** [comment]
@roehrijn 
I've made some changes hopefully they are in the right area. Specifically I've removed the check for template name and now if there is nothing defined I set something random. This will hopefully help when we come to cleaning up old tasks.

**Pull request merged**
